### ISSUE TITLE
Python 3.8 not supported (ptime.py: time.clock() has been removed)

### ISSUE THREAD

**Issue by matthew-e-brown** [jonnyhyman/Chaos#11]
Trying to run `logistic_interactive.py` with Python 3.8 or higher (3.8.1 is current) raises an error.
```
$ python logistic_interactive.py
Traceback (most recent call last):
  File "logistic_interactive.py", line 19, in <module>
    import pyqtgraph as pg
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\__init__.py", line 204, in <module>
    from .graphicsItems.VTickGroup import *
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\graphicsItems\VTickGroup.py", line 7, in <module>
    from .. import functions as fn
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\functions.py", line 17, in <module>
    from . import debug
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\debug.py", line 11, in <module>
    from . import ptime
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\ptime.py", line 24, in <module>
    cstart = systime.clock()  ### Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'
```

From [Python 3.8 documentation][1]:
> The function `time.clock()` has been removed, after having been deprecated since Python 3.3: use [`time.perf_counter()`][c] or [`time.process_time()`][b] instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in [bpo-36895][c].)

This will probably require a change on the part of either `ptime` or `pyqtgraph`. It doesn't seem too complicated, this is the file throwing the error:

```python
# -*- coding: utf-8 -*-
"""
ptime.py -  Precision time function made os-independent (should have been taken care of by python)
Copyright 2010  Luke Campagnola
Distributed under MIT/X11 license. See license.txt for more infomation.
"""


import sys
import time as systime
START_TIME = None
time = None

def winTime():
    """Return the current time in seconds with high precision (windows version, use Manager.time() to stay platform independent)."""
    return systime.clock() + START_TIME
    #return systime.time()

def unixTime():
    """Return the current time in seconds with high precision (unix version, use Manager.time() to stay platform independent)."""
    return systime.time()

if sys.platform.startswith('win'):
    cstart = systime.clock()  ### Required to start the clock in windows
    START_TIME = systime.time() - cstart
    
    time = winTime
else:
    time = unixTime
```

Because of the fact that [ptime hasn't been updated since 2017][2], I feel like it's likely Python has a more native implementation now. This will require some looking into.

[1]: https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals
[a]: https://docs.python.org/3/library/time.html#time.perf_counter 
[b]: https://docs.python.org/3/library/time.html#time.process_time
[c]: https://bugs.python.org/issue36895
[2]: https://pypi.org/project/ptime/

**Comment by jonnyhyman** [comment]
Pyqtgraph on conda (`conda install pyqtgraph`) [has resolved this](https://github.com/conda-forge/pyqtgraph-feedstock/issues/10)

Pyqtgraph on conda on PyPi (`pip install pyqtgraph`) seems to have a [temporary fix 0.11rc0 package](https://github.com/pyqtgraph/pyqtgraph/issues/1077)

Seems the standard pyqtgraph install won't work until pyqtgraph updates to 0.11

Will add a comment to `README.md`
