### ISSUE TITLE
code_generator/extracts.c:20:10: fatal error: stdio.h: No such file or directory

### ISSUE THREAD

**Issue by derrend** [jonnyhyman/Chaos#13]
$ lsb_release -a
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia

$ pip install pyqt5
Collecting PyQt5==5.14.1
  Using cached https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  Complete output from command /home/derrend/PycharmProjects/Chaos/venv/bin/python /home/derrend/PycharmProjects/Chaos/venv/lib/python3.6/site-packages/pip-19.0.3-py3.6.egg/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mfwk9_tw/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- "sip >=5.0.1, <6" "PyQt-builder >=1.1.0, <2":
  Collecting sip<6,>=5.0.1
    Using cached https://files.pythonhosted.org/packages/0d/13/fd58831e545b153cc4d803da46c1666512a9e3d4210f7c7f5b70ccfdb157/sip-5.1.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting PyQt-builder<2,>=1.1.0
    Using cached https://files.pythonhosted.org/packages/62/90/67ca5da07e8f0326067d321011d6af9e610e5debb9e5c2c66419d8d36787/PyQt_builder-1.2.0-py3-none-any.whl
  Collecting toml (from sip<6,>=5.0.1)
    Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
  Collecting packaging (from sip<6,>=5.0.1)
    Using cached https://files.pythonhosted.org/packages/98/42/87c585dd3b113c775e65fd6b8d9d0a43abe1819c471d7af702d4e01e9b20/packaging-20.1-py2.py3-none-any.whl
  Collecting pyparsing>=2.0.2 (from packaging->sip<6,>=5.0.1)
    Using cached https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl
  Collecting six (from packaging->sip<6,>=5.0.1)
    Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
  Building wheels for collected packages: sip
    Building wheel for sip (PEP 517): started
    Building wheel for sip (PEP 517): finished with status 'error'
    Complete output from command /home/derrend/PycharmProjects/Chaos/venv/bin/python /home/derrend/PycharmProjects/Chaos/venv/lib/python3.6/site-packages/pip-19.0.3-py3.6.egg/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp9uku48lh:
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/py_versions.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/__init__.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/buildable.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/abstract_project.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/distutils_builder.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/configurable.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/builder.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/bindings.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/api.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/version.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/project.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/helpers.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/installable.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/abstract_builder.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/argument_parser.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/pyproject.py -> build/lib.linux-x86_64-3.6/sipbuild
    copying sipbuild/exceptions.py -> build/lib.linux-x86_64-3.6/sipbuild
    creating build/lib.linux-x86_64-3.6/sipbuild/tools
    copying sipbuild/tools/wheel.py -> build/lib.linux-x86_64-3.6/sipbuild/tools
    copying sipbuild/tools/__init__.py -> build/lib.linux-x86_64-3.6/sipbuild/tools
    copying sipbuild/tools/install.py -> build/lib.linux-x86_64-3.6/sipbuild/tools
    copying sipbuild/tools/build.py -> build/lib.linux-x86_64-3.6/sipbuild/tools
    copying sipbuild/tools/sdist.py -> build/lib.linux-x86_64-3.6/sipbuild/tools
    creating build/lib.linux-x86_64-3.6/sipbuild/distinfo
    copying sipbuild/distinfo/distinfo.py -> build/lib.linux-x86_64-3.6/sipbuild/distinfo
    copying sipbuild/distinfo/__init__.py -> build/lib.linux-x86_64-3.6/sipbuild/distinfo
    copying sipbuild/distinfo/main.py -> build/lib.linux-x86_64-3.6/sipbuild/distinfo
    creating build/lib.linux-x86_64-3.6/sipbuild/module
    copying sipbuild/module/__init__.py -> build/lib.linux-x86_64-3.6/sipbuild/module
    copying sipbuild/module/module.py -> build/lib.linux-x86_64-3.6/sipbuild/module
    copying sipbuild/module/abi_version.py -> build/lib.linux-x86_64-3.6/sipbuild/module
    copying sipbuild/module/main.py -> build/lib.linux-x86_64-3.6/sipbuild/module
    creating build/lib.linux-x86_64-3.6/sipbuild/legacy
    copying sipbuild/legacy/__init__.py -> build/lib.linux-x86_64-3.6/sipbuild/legacy
    copying sipbuild/legacy/sip5.py -> build/lib.linux-x86_64-3.6/sipbuild/legacy
    creating build/lib.linux-x86_64-3.6/sipbuild/module/source
    creating build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/objmap.c -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/setup.cfg.in -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/threads.c -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/sip.h.in -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/sip.pyi -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/qtlib.c -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/setup.py.in -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/sipint.h -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/int_convertors.c -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/pyproject.toml -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/siplib.c -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/voidptr.c -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/array.c -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/apiversions.c -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/MANIFEST.in -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/descriptors.c -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/README.in -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/sip.rst.in -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/array.h -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    copying sipbuild/module/source/12.7/bool.cpp -> build/lib.linux-x86_64-3.6/sipbuild/module/source/12.7
    warning: build_py: byte-compiling is disabled, skipping.
  
    running build_ext
    building 'sipbuild.code_generator' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/code_generator
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Icode_generator -I/home/derrend/PycharmProjects/Chaos/venv/include -I/usr/include/python3.6m -c code_generator/extracts.c -o build/temp.linux-x86_64-3.6/code_generator/extracts.o
    code_generator/extracts.c:20:10: fatal error: stdio.h: No such file or directory
     #include <stdio.h>
              ^~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
    ----------------------------------------
    Failed building wheel for sip
    Running setup.py clean for sip
  Failed to build sip
  Could not build wheels for sip which use PEP 517 and cannot be installed directly
  
  ----------------------------------------

Command "/home/derrend/PycharmProjects/Chaos/venv/bin/python /home/derrend/PycharmProjects/Chaos/venv/lib/python3.6/site-packages/pip-19.0.3-py3.6.egg/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mfwk9_tw/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- "sip >=5.0.1, <6" "PyQt-builder >=1.1.0, <2"" failed with error code 1 in None

**Comment by jonnyhyman** [comment]
This looks to be a problem with pyqt5 on Linux, not this repository. Please direct your issue their way!
