### ISSUE TITLE
3D Mandelbrot Set changes my mind

### ISSUE THREAD

**Issue by randomwangran** [jonnyhyman/Chaos#16]
You change my mind.

Great piece!

Following is  a chinese poem by the most accomplished figures in classical Chinese literature.

题西林壁
[苏轼](https://en.wikipedia.org/wiki/Su_Shi)
横看成岭侧成峰，远近高低各不同。
不识庐山真面目，只缘身在此山中。

**Comment by jonnyhyman** [comment]
Thank you :)
