### ISSUE TITLE
Issue with logistic interactive

### ISSUE THREAD

**Issue by Jawachan** [jonnyhyman/Chaos#17]
So when I use the command to open the program this comes up:
(base) C:\Users\JAWAD SAEED\Desktop\Chaos-master>logistic_interactive.py
Traceback (most recent call last):
  File "C:\Users\JAWAD SAEED\Desktop\Chaos-master\logistic_interactive.py", line 13, in <module>
    from PyQt5.QtCore import Qt
ImportError: DLL load failed: %1 is not a valid Win32 application.
I would appreciate if someone can assist me as I need this program for a research event.
I am on windows 10 on dell latitude e6400 with the anaconda python 3.7 version and also installed all the other required prerequisites/

**Comment by jonnyhyman** [comment]
Looks like an error with PyQt5 installation. Not sure, but I would google around about this error. I think I've had it in the past but don't remember why
