### ISSUE TITLE
KeyError: 'colormap name nipy_spectral_r not found'

### ISSUE THREAD

**Issue by sebastianfdez** [jonnyhyman/Chaos#19]
Hello!

I'm having this error running: `python3 logistic_mandelbrot.py`

![image](https://user-images.githubusercontent.com/17834635/76161403-88870d80-6133-11ea-821c-fcf2714ca9ee.png)

P.S: Amazing job! Thanks

**Comment by jonnyhyman** [comment]
Looks as though you have not installed `matplotlib`? Try `pip install matplotlib`

**Comment by sebastianfdez** [comment]
That was the reason. Thanks !
