### ISSUE TITLE
VisPy Mandelbrot Resolution

### ISSUE THREAD

**Issue by nautis** [jonnyhyman/Chaos#20]
I'm getting a **very blurry** version of the really awesome visualization you have. I'm guessing this is just a limitation of my video card. Everything else is working perfectly. Do you think this is a video card problem? I have a Radeon Pro Vega 20 4 GB on on a 2.9 GHz 6-Core Intel Core i9 MacBook.

Thank you for putting this together!

**Comment by jonnyhyman** [comment]
Solved by this: https://github.com/jonnyhyman/Chaos/issues/2

The voxel size is too small (gotta increase N)
