### ISSUE TITLE
Rendering problem with all Py scripts

### ISSUE THREAD

**Issue by craiganderson-53546** [jonnyhyman/Chaos#22]
Thanks for the great code.  I created a new Python 3.7 env on my Lenovo Yoga C930 running Win10.  When loading the PyQt5 package it erred with "spyder 4.1.2 requires pyqtwebengine<5.13; python_version >= "3", which is not installed".  The install with PyQt5 v5.14.1 succeeded with this error but Interactive.py acted very badly, no control via the GUI.  I had to install PyQt5 5.12.2 to get rid of the errors.  Interactive.py works better but all scripts act badly...

logistic_interactive.py - GUI is mostly correct but it only parts of the graphs appear.  Populations updates live, but only bits and pieces of Bifurcations appears
logistic_mandelbrot.py - GUI shows the Mandelbrot set but as soon as it starts rotating it zooms into a small section and freezes
logistic_zoom.py - Draws the cobweb completely but does not zoom.  It appears not to be frozen, but seems to be redrawing the cobweb rapidly

I see that vispy is GPU-accelerated.  My Lenovo has the Intel GPU, not NVIDIA. Is that a possible cause.  Are these possibly related to the PyQt5 lib version?   Might you have any guidance on how to see the visualizations correctly?

**Comment by jonnyhyman** [comment]
`vispy` should work on any graphics card, since it uses OpenGL 2.0 which is available on everything from smartphones to toasters these days hehe :)

Your error seems to be pointing to the use of `spyder 4.1.2` and the fact that you don't have pyqtwebengine?

Perhaps try running the commands directly from the console rather than inside of a Spyder environment?

**Comment by craiganderson-53546** [comment]
Good to know on vispy

I have pyqtwebengine... here is the pip outpt...
(py3.7_Chaos) c:\jupyter\Chaos-master>pip list | find "PyQtWebEngine"
PyQtWebEngine                      5.12.1

I did ran all scripts from the console.  I assumed it used spyder since it reports the issues with its version.  

Got any ideas?

**Comment by jonnyhyman** [comment]
Seems maybe you have PyQtWebEngine in a main environment but not in the py3.7_Chaos environment?

Are you still having this issue?
