### ISSUE TITLE
Syntax error, Line 72 in Logistic_interactive.py

### ISSUE THREAD

**Issue by BennyGodwinM** [jonnyhyman/Chaos#25]
![image](https://user-images.githubusercontent.com/71246106/93044521-bc0e9b80-f672-11ea-8b3e-046afa1f0f92.png)

This is what I am getting when I try to run the program, can you please help me in this?

**Comment by Fonata** [comment]
This looks like you are using a Python version that is too old. Instead of using Python 2, try running Python 3.

**Comment by BennyGodwinM** [comment]
> This looks like you are using a Python version that is too old. Instead of using Python 2, try running Python 3.

Thank you so much, will try!!
