### ISSUE TITLE
Error running Mandelbrot and Zoom

### ISSUE THREAD

**Issue by alxw4433** [jonnyhyman/Chaos#27]
Hello !

I'm having this error running : `python3 logistic_mandelbrot.py`
<img width="870" alt="Capture d’écran 2020-09-27 à 02 27 27 (2)" src="https://user-images.githubusercontent.com/71950917/94352740-412d8380-0069-11eb-8842-447ff2ac92b8.png">

and almost the same running : `python3 logistic_zoom.py`
<img width="860" alt="Capture d’écran 2020-09-27 à 02 27 29 (2)" src="https://user-images.githubusercontent.com/71950917/94352759-6ae6aa80-0069-11eb-892e-9dfbbdc46c5d.png">

**Comment by lohithaswadagr8** [comment]
Hi, I think you did not install a library(most probably pyopengl) Check whether you have all these:

 Vispy : pip install vispy
Matplotlib : pip install matplotlib
PyOpenGL : pip install pyopengl

(TIP: type in all these seperately in your terminal)

Reply if this method solved your problem!!!!

**Comment by alexisbr16** [comment]
> Hi, I think you did not install a library(most probably pyopengl) Check whether you have all these:
> 
> Vispy : pip install vispy
> Matplotlib : pip install matplotlib
> PyOpenGL : pip install pyopengl
> 
> (TIP: type in all these seperately in your terminal)
> 
> Reply if this method solved your problem!!!!

Thanx you for the answer, but I checked and they are all installed

<img width="1142" alt="Capture d’écran 2020-10-20 à 10 52 12" src="https://user-images.githubusercontent.com/71950917/98120084-ce0bfe00-1ead-11eb-9a3b-e51a09b1e5d5.png">

**Comment by jonnyhyman** [comment]
Most definitely a python core issue, not relevant to this repo
