### ISSUE TITLE
Logistic Mandelbrot

### ISSUE THREAD

**Issue by NevoDessau** [jonnyhyman/Chaos#28]
/Users/nevo/Desktop/anaconda3/lib/python3.7/site-packages/vispy/visuals/line/line.py:395: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('color', np.float32, 4)])
/Users/nevo/Desktop/anaconda3/lib/python3.7/site-packages/vispy/visuals/line/arrow.py:57: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('linewidth', np.float32, 1)
/Users/nevo/Desktop/anaconda3/lib/python3.7/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
Traceback (most recent call last):
  File "/Users/nevo/Downloads/Chaos-master 2/logistic_mandelbrot.py", line 455, in <module>
    relative_step_size = stepsize)
  File "/Users/nevo/Desktop/anaconda3/lib/python3.7/site-packages/vispy/scene/visuals.py", line 126, in __init__
    subclass.__init__(self, *args, **kwargs)
  File "/Users/nevo/Desktop/anaconda3/lib/python3.7/site-packages/vispy/visuals/volume.py", line 410, in __init__
    self._cmap = get_colormap(cmap)
  File "/Users/nevo/Desktop/anaconda3/lib/python3.7/site-packages/vispy/color/colormap.py", line 1037, in get_colormap
    raise KeyError('colormap name %s not found' % name)
KeyError: 'colormap name nipy_spectral_r not found'

What do I do?
I really need this I'm supposed to make a presenation about this video.

**Comment by jonnyhyman** [comment]
This was previously solved by this issue:
https://github.com/jonnyhyman/Chaos/issues/19

You need to install matplotlib! `pip install matplotlib` in command line. 

Good luck!
