### ISSUE TITLE
Runtime Error problem with running all logistic maps

### ISSUE THREAD

**Issue by sarthakg043** [jonnyhyman/Chaos#31]
I tried running 
`python logistic_mandelbrot.py`
`python logistic_interactive.py`
and other commands one by one but none of them worked.

They all output the following text
` ** On entry to DGEBAL parameter number  3 had an illegal value`
`** On entry to DGEHRD  parameter number  2 had an illegal value`
` ** On entry to DORGHR DORGQR parameter number  2 had an illegal value`
` ** On entry to DHSEQR parameter number  4 had an illegal value`
`Traceback (most recent call last):`
 ` File "logistic_mandelbrot.py", line 20, in <module>`
`    from vispy.color import get_colormaps, BaseColormap`
`  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\vispy\__init__.py", line 30, in <module>`
`    from .util import config, set_log_level, keys, sys_info  # noqa`
`  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\vispy\util\__init__.py", line 9, in <module>`
`    from .logs import logger, set_log_level, use_log_level  # noqa`
`  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\vispy\util\logs.py", line 14, in <module>`
`    import numpy as np`
`  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\__init__.py", line 305, in <module>`
`    _win_os_check()`
`  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\__init__.py", line 302, in _win_os_check`
`    raise RuntimeError(msg.format(__file__)) from None`
`RuntimeError: The current Numpy installation ('C:\\Users\\hp\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
`
*This*
![logistic code error](https://user-images.githubusercontent.com/36573495/102975143-9886a700-4525-11eb-8ee8-bd48f52989f7.png)

**Comment by 2xB** [comment]
This bug and its solutions are explained here: https://github.com/numpy/numpy/wiki/FMod-Bug-on-Windows .
