### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by wi-wi** [jonnyhyman/Chaos#36]
installed all libraries and get this error while  logistic_interactive.py was left unchanged. Editing the 3rd " moves the error to the next triple " occurence.

terminal:

h@h:/media/h/3tb/www/Chaos$ python logistic_interactive.py
  File "logistic_interactive.py", line 74
    """
      ^
SyntaxError: invalid syntax

**Comment by jonnyhyman** [comment]
What's your python version? If it's pre Python-3.6 it's probably because format strings were only introduced in 3.6

If 3.6+, try checking that all strings are either "string value" or """string value""" (always either one or three quotes on both sides)

**Comment by Wayne-Huang0** [comment]
Same issue with me as well and I’m using python 3.9

**Comment by pravin1707** [comment]
I get the same issue and I tried it with every other python version (3.6+)

**Comment by jonnyhyman** [comment]
I can't replicate this... All I can say is go through the code and confirm all quotes are closed and all curly braces are formatted correctly
