### ISSUE TITLE
Animation Stuck at T=100

### ISSUE THREAD

**Issue by PAla46** [jonnyhyman/Chaos#4]
when i hit play it starts the graph plotting and stops at T=100 and then does nothing
I am using a windows machine with python 3.7
Also in the logistic_interactive.py  i am not able to choose auto instead of manual

**Comment by jonnyhyman** [comment]
You can change `self.fmax = 100` on line 660 to any number up to 1000 if you want to continue playback. Anything higher than 1000 iterations would require changing the simulation inputs.

Also, I'm not sure what you mean by auto instead of manual?

**Comment by PAla46** [comment]
![image](https://user-images.githubusercontent.com/60479636/73519933-601b3d80-4428-11ea-9bd4-b54d9be87edc.png)

i changed the number from 100 to 1000 and still stops at 100 and this is want i mean by from manual to auto

**Comment by jonnyhyman** [comment]
Ah, right try out changing `cobweb_n = 100` to 500 on line 229. I just tested and this should work. Please close the issue if it works for you.

As for that manual/auto control: we are *programmatically* changing the x-axis limits in the function `series_plot`. If you want to turn off that functionality I'd suggest modifying that function. The manual/auto control is from pyqtgraph and how it handles fitting data into the view.

**Comment by jonnyhyman** [comment]
Did that fix work for you? Closing issue by tomorrow if no reply :)

**Comment by PAla46** [comment]
it worked i changed both the values of cobwe_n and self.fmax thanks.
but i didn't understand manual/auto control
