### ISSUE TITLE
Error: TypeError: setValue(self, int): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by vitto013** [jonnyhyman/Chaos#45]
TypeError: setValue(self, int): argument 1 has unexpected type 'float' in logistic_interactive.py

**Comment by subhajitbn** [comment]
Have run into the same problem. Any way to fix it?

**Comment by Yash5675** [comment]
try this in logistic_interactive.py
at line 533: 
self.rate.setValue( int(linear_interp(self.rateval, 0, 3.99, 0, 99, lim=1, dec=2)) )
at line 551: 
self.rate.setValue( int(linear_interp(self.rateval,0, 3.99, 0, 99, lim=1, dec=2)) )

**Comment by jonnyhyman** [comment]
Solved by 426085e614231bb1950286200c2e800db17bc699
