### ISSUE TITLE
Error: AttributeError: vispy.visuals.volume has no attribute FRAG_SHADER on line 446 in logistic_mandelbrot.py

### ISSUE THREAD

**Issue by Yash5675** [jonnyhyman/Chaos#47]
I have installed all the requirements but when I try to open the `logistic_mandelbrot.py` .  It shows up:

    File "C:\Users\ambay\my_codes\python\Chaos_graph\logistic_mandelbrot.py", line 446, in <module>
        NEW_TRANSLUCENT_FRAG_SHADER = vispy.visuals.volume.FRAG_SHADER.format(
    AttributeError: module 'vispy.visuals.volume' has no attribute 'FRAG_SHADER'. Did you mean: '_FRAGMENT_SHADER'?

Please, help me how to solve this.

**Comment by MilusicJ** [comment]
I have the same problem over here

**Comment by jonnyhyman** [comment]
Hey @Yash5675 and @MilusicJ  this issue has been solved by 9d05453274f6ff876bdb04ac4645ad00d498115e. Pull the new master branch and try again!
