### ISSUE TITLE
Help!! 

### ISSUE THREAD

**Issue by spiderpro** [jonnyhyman/Chaos#48]
File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 480, in <lambda>
    self.rate_box.valueChanged.connect(lambda: self.setValues('rate_box'))
  File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 533, in setValues
    self.rate.setValue( linear_interp(self.rateval,
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "C:\Users\user01\AppData\Local\Programs\Python\Python310\lib\idlelib\run.py", line 578, in runcode
    exec(code, self.locals)
  File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 746, in <module>
    w = Widget(app)
  File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 575, in __init__
    self.controls.setValues()
  File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 560, in setValues
    self.setValues('rate_box')
  File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 533, in setValues
    self.rate.setValue( linear_interp(self.rateval,
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by makdrive3** [comment]
Hi 
I am getting the same error

**Comment by makdrive3** [comment]
> File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 480, in self.rate_box.valueChanged.connect(lambda: self.setValues('rate_box')) File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 533, in setValues self.rate.setValue( linear_interp(self.rateval, TypeError: setValue(self, int): argument 1 has unexpected type 'float' Traceback (most recent call last): File "C:\Users\user01\AppData\Local\Programs\Python\Python310\lib\idlelib\run.py", line 578, in runcode exec(code, self.locals) File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 746, in w = Widget(app) File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 575, in **init** self.controls.setValues() File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 560, in setValues self.setValues('rate_box') File "C:\Users\user01\Desktop\Chaos-master\logistic_interactive.py", line 533, in setValues self.rate.setValue( linear_interp(self.rateval, TypeError: setValue(self, int): argument 1 has unexpected type 'float'

here is how i fixed it on every line where it throws am error.
replace self.rate.setValue(linear_interp(self.rateval,
                                            0, 3.99, 0, 99, lim=1, dec=2))
with

self.rate.setValue(int(linear_interp(self.rateval,
                                            0, 3.99, 0, 99, lim=1, dec=2)))

**Comment by jonnyhyman** [comment]
Thanks for that makdrive3, this issue has been solved by Commit 426085e614231bb1950286200c2e800db17bc699
