### ISSUE TITLE
No such file or directory: './data/fractal_mandelbrot_data1000_iter1500_ovs16.npz'

### ISSUE THREAD

**Issue by Shubh-Raj** [jonnyhyman/Chaos#5]
No such file or directory: './data/fractal_mandelbrot_data1000_iter1500_ovs16.npz'

This shows up when i change the data as D=1000 and 0max=16 and try to run.

_Originally posted by @Shubh-Raj in https://github.com/jonnyhyman/Chaos/issues/2#issuecomment-580339855_

**Comment by jonnyhyman** [comment]
set `generate=True` on line 330. Does that work?
