### ISSUE TITLE
syntax error?

### ISSUE THREAD

**Issue by moloff** [jonnyhyman/Chaos#9]
I get this when I type python logistic_interactive.py into Terminal on Mac

File "logistic_interactive.py", line 73
    }}"""
        ^
SyntaxError: invalid syntax

**Comment by jonnyhyman** [comment]
What version python are you running?

That syntax error seems to be from an f-string / format-string which were only implemented in Python 3.6.

Please mark as closed if this solves your problem!

**Comment by moloff** [comment]
3.8    :(

**Comment by prat8897** [comment]
@moloff you should try running `python3 logistic_interactive.py` into Terminal on Mac instead.
